# Generated by Django 4.0.7 on 2022-09-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcyang', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcyangteammember',
            name='Team_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mcyangteam',
            name='Group_number',
            field=models.IntegerField(null=True),
        ),
    ]
