# Generated by Django 4.0.7 on 2022-09-19 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcyang', '0002_mcyangteammember_team_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcyangteamdesc',
            name='TD_status',
            field=models.IntegerField(null=True),
        ),
    ]
